name: Concretize Stack

on: [pull_request]

jobs:
  concretize:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu24]
        target: [release, release-debug]
    uses: ./.github/workflows/concretize-template.yaml
    with:
      target: ${{ matrix.target }}
      os: ${{ matrix.os }}